# Generated by Django 4.2.7 on 2023-12-20 14:03

import dcapi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationСomponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentsnumber', models.IntegerField(db_column='componentsnumber', default=0)),
            ],
            options={
                'db_table': 'creationcomponents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', dcapi.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('componentid', models.BigAutoField(primary_key=True, serialize=False)),
                ('componentname', models.CharField(max_length=100)),
                ('componentprice', models.IntegerField()),
                ('componentimage', models.CharField(max_length=100000)),
                ('componentdescription', models.CharField(blank=True, max_length=10000, null=True)),
                ('componentstatus', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'components',
            },
        ),
        migrations.CreateModel(
            name='DatacenterCreations',
            fields=[
                ('creationid', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('creationformdate', models.DateTimeField(blank=True, null=True)),
                ('creationcompleteddate', models.DateTimeField(blank=True, null=True)),
                ('creationstatus', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(db_column='useremail', default='null', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datacentercreations',
            },
        ),
    ]
