# Generated by Django 4.2.7 on 2023-12-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creationсomponents',
            options={},
        ),
    ]
