# Generated by Django 4.2.7 on 2023-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacentercreations',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
