# Generated by Django 4.2.7 on 2023-12-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcapi', '0002_alter_creationсomponents_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creationсomponents',
            options={'managed': False},
        ),
    ]
